name: CI

on:
  pull_request:


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: script
        run: ./script.sh
      - run: |
          echo 'stdout: ${{ steps.script.outputs.stdout }}'
          echo 'MY_OUTPUT: ${{ steps.script.outputs.MY_OUTPUT }}'

