name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat <<EOD > comment.txt
            test!!!!
            foo
            bar
          EOD
          gh pr comment '${{ github.event.pull_request.number }}' --body-file comment.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
