name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: passwd
        run: |
          echo "::set-output name=OUTPUT::$(jq --raw-input --slurp /etc/passwd)"
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./script.js')
            script()
