name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      apply:
        description: Apply or not
        type: boolean
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.apply }}
      - run: echo Hello
        if: github.event.inputs.apply
      - run: if [[ '${{ github.event.inputs.apply }}' == "true" ]]; then echo APPLY; fi
