name: Release

on:
  workflow_dispatch:
    inputs:
      release_note:
        description: Release note
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://githubchangeloggenerator/github-changelog-generator:1.16.2
        with:
          args: '--user yykamei --project playground'
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat CHANGELOG.md
