name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      apply:
        description: Apply or not
        type: boolean
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.apply }}
      - uses: yykamei/actions-release-actions@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.version }}
          title: Release v${{ github.event.inputs.version }}
          apply: ${{ github.event.inputs.apply }}
